# Generated by Django 3.0.3 on 2020-12-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_auto_20201221_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupImage', models.ImageField(default='default.jpg', upload_to='train')),
                ('PersonImage', models.ImageField(default='default.jpg', upload_to='test')),
                ('ResultImage', models.ImageField(default='default.jpg', upload_to='test')),
            ],
        ),
    ]
