# Generated by Django 3.0.3 on 2020-12-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimages',
            name='GroupImage',
            field=models.ImageField(upload_to='train'),
        ),
        migrations.AlterField(
            model_name='testimages',
            name='PersonImage',
            field=models.ImageField(upload_to='test'),
        ),
        migrations.AlterField(
            model_name='testimages',
            name='ResultImage',
            field=models.ImageField(upload_to='test'),
        ),
    ]
